services:
  website:
    build:
      context: website
      dockerfile: Dockerfile
    container_name: teamb-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - VIRTUAL_HOST=teamb.com.py,www.teamb.com.py
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=teamb.com.py,www.teamb.com.py

  backend:
    build:
      context: server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=api.teamb.com.py,www.api.teamb.com.py
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=api.teamb.com.py,www.api.teamb.com.py

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  certs:
  html:
  vhostd: