services:
  teamb-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000" 

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf  # Montar el archivo completo de nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt  # Monta el directorio de certificados
    depends_on:
      - teamb-app