version: '3.8'

services:
  teamb-app:
    build: .
    ports:
      - "5173:5173"
      - "4173:4173"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
    environment:
      - NODE_ENV=development
