version: '3.8'

services:
  teamb-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
      - /etc/letsencrypt:/etc/letsencrypt:ro # Montar los certificados
    ports:
      - "80:80" 
      - "443:443"
    environment:
      - NODE_ENV=production
