services:
  teamb-app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000" 
      
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - teamb-app

volumes:
  certs: