name: deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on:
      - self-hosted

    steps:
      - uses: actions/checkout@v2

      - name: Deploy on docker
        run: |
          docker compose -f docker-compose.prod.yml up -d --build
